### ISSUE TITLE
Code Cleaning: Color Variables

### ISSUE THREAD

**Issue by grantemj** [jchanes04/truth-or-dare-bot#10]
Currently, all of the colors that are used throughout the code are hardcoded. Having one place that defines which colors are used for each category of usages would help consistency and readability (to a degree with the later).

#### Example:
```javascript
const truthDareColor = '#e67e21';
const paranoiaColor = '#9b59b5';
const settingsColor = '#e73c3b';
```

**Comment by jchanes04** [comment]
Committed and pushed
