### ISSUE TITLE
Paranoia: "This interaction failed"

### ISSUE THREAD

**Issue by grantemj** [jchanes04/truth-or-dare-bot#12]
## Issue
Paranoia will send the questions to the DMs, but does not "publish" the answers to the servers.

## Behavior
![image](https://user-images.githubusercontent.com/47126361/123532970-6a05a680-d6d7-11eb-8011-164ef8ab51cb.png)

 > We used it, answered but no answers were posted on the server, and if we use the command again it says the user has an active question I used `clearparanoia` but still ddnt work

## Reported By
*(Not exhaustive)*
* Dackattack#0252
* mirage#9994
* 🤍Spicy#7979
* Lorax&lazy#4500
* KittyCatAidan#4505
* Zoonie#9087
* Bhuvan25#1229

**Comment by jchanes04** [comment]
This was due to shards 0-15 being down, I've fixed the issue with that server and now all of those shards are back online.
