### ISSUE TITLE
everything disabled automatically after using ```+en all```

### ISSUE THREAD

**Issue by AniruddhaSoni** [jchanes04/truth-or-dare-bot#14]
When I used 
```
+en server all
```
Every single category has been disabled from the channel and server.
Like every normal user I tried to kick and re-invite bot, but everything goes into vain.

**Comment by jchanes04** [comment]
This issue has hopefully been fixed with the latest changes. They have been committed to this repo, so if the issue persists then you can take a look at the enableCommand.js and disableCommand.js files to try and find the source of the problem.
