### ISSUE TITLE
Paranoia not showing questions

### ISSUE THREAD

**Issue by HazeG** [jchanes04/truth-or-dare-bot#16]
Paranoia currently does not show any questions, when trying to use the command to show all it does not work, and the default is not showing any questions as of right now

**Comment by jchanes04** [comment]
Does showparanoia being set to "all" change this?

**Comment by HazeG** [comment]
Tried with both the command and the / command both are not accepted, the / command gets interaction error and the show paranoia all command does not work at all

**Comment by HazeG** [comment]
I have seen other people report the same bug/error on the support discord so i guess its a general error with paranoia, also tried the beta bot which has the same error

**Comment by jchanes04** [comment]
I've updated the permission check in showParanoia, that should stop it from erroring. As far as none of the questions showing, it's either bad luck or an error in fetching the channel settings. Hopefully that issue is resolved as well.

**Comment by jchanes04** [comment]
The errors that were causing issues should no longer appear. I'll mark as resolved, but reopen in case issues persist.
