### ISSUE TITLE
Block Specific Questions in a Server

### ISSUE THREAD

**Issue by grantemj** [jchanes04/truth-or-dare-bot#4]
This was mentioned in the support server by Registry Editor#3293

> The ability to block certain questions in a server would be nice
> proposed syntax
`+block <question id> <time where 0 = permanent>`

**Comment by jchanes04** [comment]
This is most likely going to a feature on the premium version of the bot, as it fits very well with the other kinds of features I have planned. Expect to see changes appear here on the beta, but not make it into the main version until premium is released.

**Comment by jchanes04** [comment]
I've added this functionality in the remove command on the premium branch.
